name: CI
on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps (prefer npm ci, fallback to npm install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      - name: Lint (optional)
        run: npm run lint --if-present

      - name: Typecheck (optional)
        run: npx tsc --noEmit || true

      - name: Build
        run: npm run build

      - name: Build Storybook (optional)
        run: npm run build-storybook --if-present

  e2e:
    needs: build
    runs-on: ubuntu-latest
    env:
      CI: true
      NEXT_TELEMETRY_DISABLED: 1
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi

      # ✅ This action installs the correct system packages AND Playwright browsers
      - name: Install Playwright (browsers + deps)
        uses: microsoft/playwright-github-action@v1

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Playwright report (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
          retention-days: 7
