name: CI
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, codex/**, feature/**, fix/** ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20 (with npm cache)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install deps (npm ci with fallback)
        run: npm ci || npm install

      - name: Build Next.js
        run: npm run build

      # Storybook & Playwright kan vi lägga till i senare PR:er.
