name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi
      - run: npm run lint --if-present
      - run: npm run build
      - name: Build Storybook (only if stories present)
        run: |
          if ls components/**/*.stories.* 1> /dev/null 2>&1; then
            npm run build-storybook || npx -y storybook@8.1.4 build
          else
            echo "No stories found, skipping Storybook build."
          fi
      - name: Install Playwright browsers
        run: npx playwright install --install-deps=true
      - run: npm run test:e2e --if-present
