name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install deps (prefer npm ci, fallback to npm install)
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm install
          else
            npm install
          fi
      - run: npm run lint --if-present
      - run: npm run build
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - run: npm run test:e2e --if-present
